# --------------------------------------------------------------------------------------------------
#
#   Stellars Jupyterhub DS Platform 
#   Project Home: https://github.com/stellarshenson/stellars-jupyterhub-ds
#   This file adds GPU support to compose.yml services
#
# --------------------------------------------------------------------------------------------------

services:

  ## adds NVIDIA GPU support to Jupyterhub service
  jupyterhub:
    environment:
      - GPU_SUPPORT_ENABLED=1
    deploy:
       resources:
         reservations:
           devices:
             - driver: nvidia
               count: all
               capabilities: [gpu]

# EOF

