"""SQLAlchemy event listeners for user lifecycle synchronization."""

import contextvars
import html
import os


# The acting admin for an in-flight rename, set by the rename API handler so the
# recorded event can name WHO renamed whom. None when a rename happens outside a
# request context (then the event falls back to the actor-less form).
_rename_actor = contextvars.ContextVar("rename_actor", default=None)


def set_rename_actor(name):
    """Tag the current context with the admin performing a rename; the listener
    reads this to attribute the recorded event. Returns a reset token."""
    return _rename_actor.set(name)


def reset_rename_actor(token):
    """Clear the rename actor set by set_rename_actor (pass its token)."""
    _rename_actor.reset(token)


def register_events():
    """Register all SQLAlchemy event listeners. Call once from jupyterhub_config.py."""
    from sqlalchemy import event
    from jupyterhub import orm

    @event.listens_for(orm.User.name, 'set')
    def sync_nativeauth_on_rename(target, value, oldvalue, initiator):
        """Sync NativeAuthenticator UserInfo and ActivityMonitor when User.name changes."""
        if oldvalue == value or oldvalue is None:
            return

        # Sync NativeAuthenticator
        try:
            from nativeauthenticator.orm import UserInfo
            from sqlalchemy.orm import object_session

            session = object_session(target)
            if session:
                user_info = session.query(UserInfo).filter(UserInfo.username == oldvalue).first()
                if user_info:
                    user_info.username = value
                    print(f"[NativeAuth Sync] Queued UserInfo rename: {oldvalue} -> {value}")
        except ImportError:
            pass
        except Exception as e:
            print(f"[NativeAuth Sync] Error: {e}")

        # Sync ActivityMonitor
        try:
            from .activity.helpers import rename_activity_user
            rename_activity_user(oldvalue, value)
        except Exception as e:
            print(f"[ActivityMonitor Sync] Error renaming: {e}")

        # Sync the display profile (first/last name + email) to the new username
        try:
            from .user_profiles import UserProfileManager
            UserProfileManager.get_instance().rename_user(oldvalue, value)
        except Exception as e:
            print(f"[UserProfile Sync] Error renaming: {e}")

        from .event_log import record_event
        old_b = f'<b>{html.escape(str(oldvalue))}</b>'
        new_b = f'<b>{html.escape(str(value))}</b>'
        actor = _rename_actor.get()
        if actor:
            # who renamed whom - the admin who triggered the rename API call
            record_event('user', f'<b>{html.escape(str(actor))}</b> renamed {old_b} to {new_b}')
        else:
            record_event('user', f'{old_b} renamed to {new_b}')

    @event.listens_for(orm.User, 'after_insert')
    def create_nativeauth_on_user_insert(mapper, connection, target):
        """Auto-create NativeAuthenticator UserInfo when a new User is created via admin panel.
        Generates a memorable password using xkcdpass and auto-approves the user.
        """
        username = target.name
        try:
            import bcrypt
            from xkcdpass import xkcd_password as xp
            from sqlalchemy import text

            result = connection.execute(
                text("SELECT id FROM users_info WHERE username = :username"),
                {"username": username},
            )
            if result.fetchone():
                print(f"[NativeAuth Auto-Create] UserInfo already exists for: {username}")
                return

            num_words = int(os.environ.get('JUPYTERHUB_AUTOGENERATED_PASSWORD_WORDS', 4))
            delimiter = os.environ.get('JUPYTERHUB_AUTOGENERATED_PASSWORD_DELIMITER', '-')
            wordfile = xp.locate_wordfile()
            words = xp.generate_wordlist(wordfile=wordfile, min_length=4, max_length=6)
            password = xp.generate_xkcdpassword(words, numwords=num_words, delimiter=delimiter)

            hashed_password = bcrypt.hashpw(password.encode('utf-8'), bcrypt.gensalt())

            connection.execute(
                text("INSERT INTO users_info (username, password, is_authorized) VALUES (:username, :password, 1)"),
                {"username": username, "password": hashed_password},
            )

            from .password_cache import cache_password
            cache_password(username, password)

            try:
                from .activity.helpers import initialize_activity_for_user
                initialize_activity_for_user(username)
            except Exception as ae:
                print(f"[Activity Init] Error initializing activity for {username}: {ae}")

            print(f"[NativeAuth Auto-Create] User '{username}' created and authorized")

        except Exception as e:
            print(f"[NativeAuth Auto-Create] Error for {username}: {e}")

        from .event_log import record_event
        record_event('user', f'<b>{html.escape(str(username))}</b> was created')

    @event.listens_for(orm.User, 'after_delete')
    def remove_nativeauth_on_user_delete(mapper, connection, target):
        """Remove NativeAuthenticator UserInfo and ActivityMonitor data when a User is deleted."""
        username = target.name

        try:
            from sqlalchemy import text

            result = connection.execute(
                text("DELETE FROM users_info WHERE username = :username"),
                {"username": username},
            )
            if result.rowcount > 0:
                print(f"[NativeAuth Cleanup] Removed UserInfo for deleted user: {username}")

            try:
                from .password_cache import clear_cached_password
                clear_cached_password(username)
            except ImportError:
                pass
        except Exception as e:
            print(f"[NativeAuth Cleanup] Error removing UserInfo for {username}: {e}")

        try:
            from .activity.helpers import delete_activity_user
            delete_activity_user(username)
        except Exception as e:
            print(f"[ActivityMonitor Cleanup] Error removing data for {username}: {e}")

        try:
            from .user_profiles import UserProfileManager
            UserProfileManager.get_instance().delete_profile(username)
        except Exception as e:
            print(f"[UserProfile Cleanup] Error removing profile for {username}: {e}")

        from .event_log import record_event
        record_event('user', f'<b>{html.escape(str(username))}</b> was deleted')
