"""SQLAlchemy event listeners for user lifecycle synchronization."""

import os


def register_events():
    """Register all SQLAlchemy event listeners. Call once from jupyterhub_config.py."""
    from sqlalchemy import event
    from jupyterhub import orm

    @event.listens_for(orm.User.name, 'set')
    def sync_nativeauth_on_rename(target, value, oldvalue, initiator):
        """Sync NativeAuthenticator UserInfo and ActivityMonitor when User.name changes."""
        if oldvalue == value or oldvalue is None:
            return

        # Sync NativeAuthenticator
        try:
            from nativeauthenticator.orm import UserInfo
            from sqlalchemy.orm import object_session

            session = object_session(target)
            if session:
                user_info = session.query(UserInfo).filter(UserInfo.username == oldvalue).first()
                if user_info:
                    user_info.username = value
                    print(f"[NativeAuth Sync] Queued UserInfo rename: {oldvalue} -> {value}")
        except ImportError:
            pass
        except Exception as e:
            print(f"[NativeAuth Sync] Error: {e}")

        # Sync ActivityMonitor
        try:
            from .activity.helpers import rename_activity_user
            rename_activity_user(oldvalue, value)
        except Exception as e:
            print(f"[ActivityMonitor Sync] Error renaming: {e}")

    @event.listens_for(orm.User, 'after_insert')
    def create_nativeauth_on_user_insert(mapper, connection, target):
        """Auto-create NativeAuthenticator UserInfo when a new User is created via admin panel.
        Generates a memorable password using xkcdpass and auto-approves the user.
        """
        username = target.name
        try:
            import bcrypt
            from xkcdpass import xkcd_password as xp
            from sqlalchemy import text

            result = connection.execute(
                text("SELECT id FROM users_info WHERE username = :username"),
                {"username": username},
            )
            if result.fetchone():
                print(f"[NativeAuth Auto-Create] UserInfo already exists for: {username}")
                return

            num_words = int(os.environ.get('JUPYTERHUB_AUTOGENERATED_PASSWORD_WORDS', 4))
            delimiter = os.environ.get('JUPYTERHUB_AUTOGENERATED_PASSWORD_DELIMITER', '-')
            wordfile = xp.locate_wordfile()
            words = xp.generate_wordlist(wordfile=wordfile, min_length=4, max_length=6)
            password = xp.generate_xkcdpassword(words, numwords=num_words, delimiter=delimiter)

            hashed_password = bcrypt.hashpw(password.encode('utf-8'), bcrypt.gensalt())

            connection.execute(
                text("INSERT INTO users_info (username, password, is_authorized) VALUES (:username, :password, 1)"),
                {"username": username, "password": hashed_password},
            )

            from .password_cache import cache_password
            cache_password(username, password)

            try:
                from .activity.helpers import initialize_activity_for_user
                initialize_activity_for_user(username)
            except Exception as ae:
                print(f"[Activity Init] Error initializing activity for {username}: {ae}")

            print(f"[NativeAuth Auto-Create] User '{username}' created and authorized")

        except Exception as e:
            print(f"[NativeAuth Auto-Create] Error for {username}: {e}")

    @event.listens_for(orm.User, 'after_delete')
    def remove_nativeauth_on_user_delete(mapper, connection, target):
        """Remove NativeAuthenticator UserInfo and ActivityMonitor data when a User is deleted."""
        username = target.name

        try:
            from sqlalchemy import text

            result = connection.execute(
                text("DELETE FROM users_info WHERE username = :username"),
                {"username": username},
            )
            if result.rowcount > 0:
                print(f"[NativeAuth Cleanup] Removed UserInfo for deleted user: {username}")

            try:
                from .password_cache import clear_cached_password
                clear_cached_password(username)
            except ImportError:
                pass
        except Exception as e:
            print(f"[NativeAuth Cleanup] Error removing UserInfo for {username}: {e}")

        try:
            from .activity.helpers import delete_activity_user
            delete_activity_user(username)
        except Exception as e:
            print(f"[ActivityMonitor Cleanup] Error removing data for {username}: {e}")
