/* Bulk add users - paste usernames (one per line), configure once for the batch,
 * then land on the result screen. Every password is auto-generated by the hub and
 * surfaced once on the result page. */
import { useState } from 'react'
import { Card, Form, Input, Switch } from 'antd'
import { useNavigate } from 'react-router-dom'
import { PageHeader } from '../components/PageHeader'
import { FormFooter } from '../components/FormFooter'
import { GroupPicker } from '../components/GroupPicker'
import { isMock } from '../services/dataMode'
import { addMember, setUserAuthorization, createUser, getCredentials } from '../services/ops'

export default function BulkUsers() {
  const navigate = useNavigate()
  const [form] = Form.useForm()
  const [groups, setGroups] = useState<string[]>([])

  const submit = async () => {
    const v = await form.validateFields().catch(() => null)
    if (!v) return
    const names = String(v.usernames ?? '')
      .split('\n')
      .map((s) => s.trim())
      .filter(Boolean)
    if (!names.length) return

    if (isMock()) {
      navigate('/users/bulk/result', { state: { groups: groups.join(', ') } })
      return
    }
    try {
      for (const name of names) {
        await createUser(name)
        for (const g of groups) await addMember(g, name)
        if (!v.authorize) await setUserAuthorization(name, false) // create auto-authorises; turn it back off
      }
      const creds = await getCredentials(names)
      navigate('/users/bulk/result', { state: { creds, groups: groups.join(', '), requested: names.length } })
    } catch {
      /* ops surfaced the error */
    }
  }

  return (
    <>
      <PageHeader title="Bulk add users" sub="Paste usernames and configure the batch once - passwords are auto-generated" />
      <Card style={{ maxWidth: 820 }}>
        <Form form={form} layout="vertical" initialValues={{ authorize: true }}>
          <Form.Item label="Usernames" name="usernames" extra="One per line">
            <Input.TextArea rows={6} placeholder={'jdoe\nasmith\nmkovac'} />
          </Form.Item>
          <Form.Item label="Groups">
            <GroupPicker value={groups} onChange={setGroups} label="" />
          </Form.Item>
          <Form.Item label="Authorise now" name="authorize" valuePropName="checked"><Switch /></Form.Item>
        </Form>
        <FormFooter onCancel={() => navigate('/users')} onSave={submit} saveLabel="Create" />
      </Card>
    </>
  )
}
